version: "3.9"

x-app: &app
  env_file:
    - ./.env
  restart: always

x-default-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '3'
  driver: json-file

services:
  source-db:
    image: postgres:13
    container_name: source-db
    <<: *app
    logging: *default-logging
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    volumes:
      - source_db_data:/var/lib/postgresql/data/
      - ./init_scripts/1_init_source_db.sql:/docker-entrypoint-initdb.d/1_init_source_db.sql
      - ./init_scripts/2_film_work_dump.sql:/docker-entrypoint-initdb.d/2_film_work_dump.sql
      - ./init_scripts/3_genre_dump.sql:/docker-entrypoint-initdb.d/3_genre_dump.sql
      - ./init_scripts/4_genre_film_work_dump.sql:/docker-entrypoint-initdb.d/4_genre_film_work_dump.sql
      - ./init_scripts/5_person_dump.sql:/docker-entrypoint-initdb.d/5_person_dump.sql
      - ./init_scripts/6_person_film_work_dump.sql:/docker-entrypoint-initdb.d/6_person_film_work_dump.sql
  target-db:
    image: elasticsearch:8.6.2
    container_name: target-db
    <<: *app
    logging: *default-logging
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled=false
    volumes:
      - target_db_data:/usr/share/elasticsearch/data
  etl:
    container_name: etl
    <<: *app
    logging: *default-logging
    build: etl
    depends_on:
      - source-db
      - target-db

volumes:
  source_db_data:
  target_db_data:
