version: "3.9"

x-app: &app
  env_file:
    - ./.env
  restart: always

x-default-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '3'
  driver: json-file

services:
  source-db:
    image: postgres:14
    container_name: source-db
    <<: *app
    logging: *default-logging
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    volumes:
      - source_db_data:/var/lib/postgresql/data/
      - ./init_scripts/init_source_db.sql:/docker-entrypoint-initdb.d/init.sql
  target-db:
    image: elasticsearch:8.6.2
    container_name: target-db
    <<: *app
    logging: *default-logging
    ports:
      - "9200:9200"
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled=false
      - http.cors.enabled=true  # todo удалить
      - http.cors.allow-origin=https://app.elasticvue.com  # todo удалить
    volumes:
      - target_db_data:/usr/share/elasticsearch/data
#  etl:
#    container_name: etl
#    <<: *app
#    logging: *default-logging
#    build: etl


volumes:
  source_db_data:
  target_db_data:
